### ISSUE TITLE
Can't detect the HyperTech Crackproof

### ISSUE THREAD

**Issue by GEEKiDoS** [horsicq/Detect-It-Easy#102]
The significant things about this packer is the kernel32.dll imported as a weird `KeRnEl32.dLl`
![image](https://user-images.githubusercontent.com/14933408/141061776-ec9930d6-81c1-4c5b-81f0-c0e1473a11ff.png)

sample file:
[Assembly-CSharp.zip](https://github.com/horsicq/Detect-It-Easy/files/7510352/Assembly-CSharp.zip)

**Comment by horsicq** [comment]
Thanks a lot for the bugreport. I will take a look,

**Comment by horsicq** [comment]
I added it to the database. The new version of DiE will be in a few days.
