### ISSUE TITLE
Linux Portable Version

### ISSUE THREAD

**Issue by paulzroe** [horsicq/Detect-It-Easy#107]
Thanks for this great tool.
I noticed that in the latest releases, there is not portable version for Linux. Will you still be making them?

**Comment by horsicq** [comment]
Hello. 

* download an appImage file https://github.com/horsicq/DIE-engine/releases/download/3.03/Detect_It_Easy-3.03-x86_64.AppImage
* make the file executable (chmod +x Detect_It_Easy-3.03-x86_64.AppImage)
* run it (./Detect_It_Easy-3.03-x86_64.AppImage)

**Comment by paulzroe** [comment]
Thanks, but the console/command mode seems to not work.

**Comment by horsicq** [comment]
What Linux do you use?

**Comment by paulzroe** [comment]
Ubuntu server

**Comment by horsicq** [comment]
Version? 20.04?

**Comment by paulzroe** [comment]
18.04

**Comment by horsicq** [comment]
Ok. I will build portable version for you.

**Comment by horsicq** [comment]
BTW. Did you try to install the DEB file? https://github.com/horsicq/DIE-engine/releases/download/3.03/die_3.03_Ubuntu_18.04_amd64.deb

**Comment by paulzroe** [comment]
Thanks. Yes, I was able to install the deb file. I just prefer the portable version.

**Comment by horsicq** [comment]
https://github.com/horsicq/DIE-engine/releases/tag/3.04
