### ISSUE TITLE
Энтропия

### ISSUE THREAD

**Issue by Plffvjjteschjyrscvbj** [horsicq/Detect-It-Easy#108]
Можно узнать по какой формуле строится график энтропии в вашей программе?

**Comment by horsicq** [comment]
Да, конечно. https://github.com/horsicq/XEntropyWidget/blob/e7411f6e26f7ef4f3b9b494d9b1a34c3394b4416/entropyprocess.cpp#L206
https://github.com/horsicq/Formats/blob/f9d77bf3f20cb968a0d91f042978e0726d5761a1/xbinary.cpp#L5376
