### ISSUE TITLE
Cannot mix incompatible Qt library

### ISSUE THREAD

**Issue by Voskrese** [horsicq/Detect-It-Easy#11]
если запустить без окружения
./die
Ошибка сегментирования

если добавить
export LD_LIBRARY_PATH=/opt/DIE-engine/lin64/stuff:$LD_LIBRARY_PATH
./die
Cannot mix incompatible Qt library (version 0x40807) with this library (version 0x40806)
Аварийный останов

из командной строки все работает, что ваша сборка, что сборка из исходников

./diec

./DIEC_lin64
Detect It Easy 1.01 console

Copyright(C) 2006-2008 Hellsp@wn 2012-2016 Hors
Website: http://ntinfo.biz
Bugreports: horsicq@gmail.com

Number of Binary signatures: 217
    Number of com signatures: 175
Number of Text signatures: 12
    Number of com signatures: 3
Number of MSDOS signatures: 275
Number of PE/PE+ signatures: 471
Number of ELF/ELF64 signatures: 16
Number of MACH/MACH64 signatures: 8
Total signatures: 999

Usage: DIEC file/directory [options]

Options:
-showerrors [default: -showerrors:no] Show all errors
-showoptions [default: -showoptions:yes] Show compiler/protector/packer/etc options
-showversion [default: -showversion:yes] Show compiler/protector/packer/etc version
-subfolders [default: -subfolders:yes] Scan subfolders. Only for directory scan
-showentropy [default: -showentropy:no] Show entropy
-singlelineoutput [default: -singlelineoutput:no] Output as single line
-showfileformatonce [default: -showfileformatonce:no] Show file format once
-fullscan [default: -fullscan:no] Full scan for all valid types
-database [default: -database:"$app/db"] Set scan database

./DIEC_lin64 die
ELF64: packer: UPX(3.91)[LZMA,brute]

**Comment by horsicq** [comment]
//Ошибка сегментирования

Какая операционная система?

// из командной строки все работает, что ваша сборка, что сборка из исходников

Можете попробовать собрать с более новой библиотекой?
http://download.qt.io/official_releases/qt/4.8/4.8.7/qt-everywhere-opensource-src-4.8.7.tar.gz

**Comment by Voskrese** [comment]
> Какая операционная система?
uname -a
Linux ubuntu 4.2.0-35-lowlatency #40-Ubuntu SMP PREEMPT Tue Mar 15 23:25:22 UTC 2016 x86_64
Ubuntu 15.10
> Можете попробовать собрать с более новой библиотекой?
qmake-qt4 -v
QMake version 2.01a
Using Qt version 4.8.7 in /usr/lib/x86_64-linux-gnu

**Comment by horsicq** [comment]
Ладно, будем разбираться. 

// кcта GUI версии в исходниках нет?! или я что то не понял

GUI это надстройка над консольной версией. Когда я приведу весь код в порядок, то выложу и её. 
Пока там есть костыли, которые очень не нравятся true Qt - программистам. И мне самому не нравятся.
Когда я начинал писать эту программу, то не знал много тонкостей Qt, типа правильной работы с потоками.
