### ISSUE TITLE
Themida version 2 not detected

### ISSUE THREAD

**Issue by dthnh175** [horsicq/Detect-It-Easy#111]
The newest version of Detect-It-Easy (v3.04 at the time) cannot detect Themida v2.

Sample: 
https://tria.ge/220220-hxdvzsahgq/static1
https://www.hybrid-analysis.com/sample/aa39dc406b5c6ece6693229839326d659ef48ddab92e083eff9063abf01a3b7b

**Comment by horsicq** [comment]
Thanks a lot for the report! But I cannot without registration download your samples.

Could you send this file me to my Telegram bot : @detectiteasy_bot

BTW did you try to scan it with NFD engine?

![image](https://user-images.githubusercontent.com/7762949/154837081-b1e94904-269f-477f-b893-b6c7fe5f8a7d.png)

**Comment by pka4916** [comment]
Funny,.   I just asked the same thing.

in DIE 2.0.5  it will detect it,  but not in DIE 3.0.1 and 3.0.4

**Comment by dthnh175** [comment]
> Could you send this file me to my Telegram bot : @detectiteasy_bot
I sent it to your Telegram bot. You can check the DM now.

> BTW did you try to scan it with NFD engine?
The result was the same - no Themida detected.
![image](https://user-images.githubusercontent.com/41712808/154967635-f764b366-46f7-4fdc-b79f-e68cc516d7b5.png)

**Comment by horsicq** [comment]
Thank you a lot we will fix it ASAP

**Comment by pka4916** [comment]
I just sent my file as well.  Quiz Studio org.zip.

**Comment by horsicq** [comment]
Thanks a lot!

**Comment by DosX-dev** [comment]
Done. ([click!](https://github.com/horsicq/Detect-It-Easy/commit/e8e25fecd1346e63e54623add0b5a3babe001d6b))
