### ISSUE TITLE
The CLI does not handle non-ascii .NET version

### ISSUE THREAD

**Issue by Catminusminus** [horsicq/Detect-It-Easy#117]
Some binaries have non-ascii .NET version as the image.
![image](https://user-images.githubusercontent.com/37803616/163355978-52e588b8-aeef-492c-b85b-e6cc02d75228.png)

The GUI handle them correctly, but the CUI doesn't.

Expected output:
```
<snip>
                {
                    "info": "-",
                    "name": ".NET",
                    "string": "Library: .NET(v4.0.30319¶)[-]",
                    "type": "Library",
                    "version": "v4.0.30319¶"
                },
<snip>
```

Actual output:
```
<snip>
                {
                    "info": "-",
                    "name": ".NET",
                    "string": "Library: .NET(v4.0.30319)[-]",
                    "type": "Library",
                    "version": "v4.0.30319"
                },
<snip>
```

You can get the expected output by using `sResult.toUtf8()` instead of `sResult.toLatin1()` in [main_console.cpp](https://github.com/horsicq/DIE-engine/blob/1b6900511402e5a86cd1b16d86f75bdf7c04f8ff/console_source/main_console.cpp), and I will create a PR to fix this.

**Comment by horsicq** [comment]
Thanks a lot for the bugreport! I will fix it.

// You can get the expected output by using sResult.toUtf8() instead of sResult.toLatin1() in [main_console.cpp](https://github.com/horsicq/DIE-engine/blob/1b6900511402e5a86cd1b16d86f75bdf7c04f8ff/console_source/main_console.cpp), and I will create a PR to fix this.

Thanks! I guess there are problems in my another project: https://github.com/horsicq/Nauz-File-Detector
So I have to research it before PR

**Comment by Catminusminus** [comment]
Thank you for your response.

> Thanks! I guess there are problems in my another project: https://github.com/horsicq/Nauz-File-Detector

Yes, I found that [Nauz-File-Detector](https://github.com/horsicq/Nauz-File-Detector) v0.07 has the same problem.

```
<snip>
                {
                    "info": "",
                    "name": ".NET",
                    "string": "Library: .NET(v4.0.30319)",
                    "type": "Library",
                    "version": "v4.0.30319"
                },
<snip>
```

As a side note that I used a malware (https://www.virustotal.com/gui/file/7c59d0ba09c236dd4f174738b079e8e0a3c6b8b38a0cdcbe3b38a2c90eaf8507) to check this. I'm sorry that I can't give the sample...

> I will fix it.

Thank you. I see.
