### ISSUE TITLE
App crash on VirusTotal page

### ISSUE THREAD

**Issue by greenozon** [horsicq/Detect-It-Easy#124]
App crash on VirusTotal page in case no API key provided
when clicking "Save" button
![image](https://user-images.githubusercontent.com/765343/179345395-7233375c-95be-45f7-a7ec-569c8176008a.png)

![image](https://user-images.githubusercontent.com/765343/179345450-dbe822d7-31e8-4a19-9aea-5ae4fb2f8cbe.png)

PS issue analyzed, root cause found,PR to be provided in a little while

**Comment by horsicq** [comment]
Thanks a lot for testing!
