### ISSUE TITLE
macOS pgk of latest release crashes on launch

### ISSUE THREAD

**Issue by yossizahn** [horsicq/Detect-It-Easy#125]
The macOS installer versions from the latest release ([die_mac_3.05.pkg](https://github.com/horsicq/DIE-engine/releases/download/3.05/die_mac_3.05.pkg) & [die_mac_qt6_3.05.pkg](https://github.com/horsicq/DIE-engine/releases/download/3.05/die_mac_qt6_3.05.pkg)) crash upon launch:
```
>$ QT_DEBUG_PLUGINS=1 /Applications/die.app/Contents/MacOS/die
QFactoryLoader::QFactoryLoader() checking directory path "/Applications/die.app/Contents/MacOS/diePlugIns/platforms" ...
QFactoryLoader::QFactoryLoader() checking directory path "/Applications/die.app/Contents/MacOS/platforms" ...
qt.qpa.plugin: Could not find the Qt platform plugin "cocoa" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

[1]    25725 abort      QT_DEBUG_PLUGINS=1 /Applications/die.app/Contents/MacOS/die
```
I managed to run it like this:
```
QT_QPA_PLATFORM_PLUGIN_PATH=/Applications/die.app/Contents/PlugIns   /Applications/die.app/Contents/MacOS/die
```

**Comment by horsicq** [comment]
Hello! Zhanks a lot for the report! I will take a look.

**Comment by horsicq** [comment]
I guess you should delete Detect It Easy from /Applications then reinstall pkg.

**Comment by yossizahn** [comment]
> I guess you should delete Detect It Easy from /Applications then reinstall pkg.

Interestingly that helped, I'm not sure why...

**Comment by horsicq** [comment]
Cause qt5 version compiled for x64 and qt6 version complied for m1 arm. If you install them both wil be a conflict.
