### ISSUE TITLE
gui has some problems

### ISSUE THREAD

**Issue by wuyudi** [horsicq/Detect-It-Easy#126]
It was fine before analysis.

![image](https://user-images.githubusercontent.com/30024051/183422044-b5490178-f92a-4252-a51d-625309a398b5.png)

but become weird after analyze

![image](https://user-images.githubusercontent.com/30024051/183426179-633b0c5f-47ab-4849-8e80-b636c70ed03c.png)

I installed it from aur.

---

I tried with Appimage

![image](https://user-images.githubusercontent.com/30024051/183426343-34f2de69-7d17-43f8-ad33-a6e73c3a88e3.png)

same problem.

**Comment by horsicq** [comment]
Hello! Thanks for the report! I will take a look.

BTW can you resize the main window?

**Comment by horsicq** [comment]
I am using Ubuntu not Arch. :( BTW could you test the program: https://github.com/horsicq/XPEViewer

Here is the portable version: https://github.com/horsicq/XPEViewer/releases/tag/0.04

Is there gui problems too?

**Comment by wuyudi** [comment]
I have resized the main window, but those frames: Sections, Time date stamp, and Size of image don't change.

![image](https://user-images.githubusercontent.com/30024051/183475842-3e3cea4f-167b-4a4f-af1c-680fb128f396.png)


XPEViewer works well

---

I found that aur hasn't it, so I made a PKGBUILD, feel free to use or publish it to aur.

```bash
pkgname=xpeviewer
pkgver=0.04
pkgrel=1
pkgdesc='PE file viewer/editor for Windows, Linux and MacOS.'
arch=(x86_64)
url="https://horsicq.github.io"
license=('MIT')
depends=('glibc')
options=('!emptydirs' '!strip')
source=("${pkgname}-${pkgver}.deb::https://github.com/horsicq/XPEViewer/releases/download/${pkgver}/xpeviewer_${pkgver}_Debian_11_amd64.deb"
        "LICENSE")
sha256sums=('6b184eef05b5cabedb6a5b2704dc6f0d23ee4c373d2894210b0aad40f8cec080'
            'f78bf193f3aebf1225e4b5be12f7184178ca4fa3a3d3444e2ac933d86af9dc68')

package() {
    tar -xJf data.tar.xz -C "${pkgdir}"/

	install -Dm644 "${srcdir}/LICENSE" "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
}
```

**Comment by horsicq** [comment]
Thanks a lot for the testing! It will be fixed in the next version of DiE.

Thanks a lot for the PKGBUILD file too!
