### ISSUE TITLE
Multiple crashes on Parrot OS 5.1

### ISSUE THREAD

**Issue by dmknght** [horsicq/Detect-It-Easy#134]
Detect It Easy version: v3.06
Problem: Program crashes when star analyzing file. For example:
1. Start Detect It Easy GUI
2. Select `/usr/bin/atril`
3. Program crashed
Some not very useful logs when i tried gdb
```
[#0] Id 1, Name: "die", stopped 0x7ffff734ec6b in ?? (), reason: SIGSEGV
[#1] Id 2, Name: "QXcbEventQueue", stopped 0x7ffff63f5def in __GI___poll (), reason: SIGSEGV
[#2] Id 3, Name: "QDBusConnection", stopped 0x7ffff63f5def in __GI___poll (), reason: SIGSEGV
[#3] Id 4, Name: "gmain", stopped 0x7ffff63f5def in __GI___poll (), reason: SIGSEGV
[#4] Id 5, Name: "gdbus", stopped 0x7ffff63f5def in __GI___poll (), reason: SIGSEGV
[#5] Id 6, Name: "Thread (pooled)", stopped 0x55555597c3a9 in ?? (), reason: SIGSEGV
[#6] Id 7, Name: "Thread (pooled)", stopped 0x7ffff63c8621 in __GI___clock_nanosleep (), reason: SIGSEGV
[#7] Id 10, Name: "dconf worker", stopped 0x7ffff63f5def in __GI___poll (), reason: SIGSEGV
[#8] Id 11, Name: "pool-die", stopped 0x7ffff63fb3a9 in syscall (), reason: SIGSEGV
[#9] Id 12, Name: "Thread (pooled)", stopped 0x55555582e902 in ?? (), reason: SIGSEGV
```
Meanwhile, the console version doesn't crash but shows no information
```
$diec /usr/bin/atril
ELF64
    Library: GLIBC(2.4)[DYN AMD64-64]
```

**Comment by horsicq** [comment]
Thanks a lot for the report! I will take a look

**Comment by horsicq** [comment]
[die_3.07_Parrot_5.1_amd64.zip](https://github.com/horsicq/Detect-It-Easy/files/9803943/die_3.07_Parrot_5.1_amd64.zip)

**Comment by horsicq** [comment]
I cannot install Qt library on the latest Parrot OS:

![qtbase5-dev](https://user-images.githubusercontent.com/7762949/196270046-81fe85fc-3a38-402e-ab52-5e65ce03c526.PNG)

**Comment by horsicq** [comment]
Fixed 
![ParrotOS](https://user-images.githubusercontent.com/7762949/196577256-6062af78-0733-4e46-ba99-5ca1bc3b7dc7.PNG)

https://github.com/horsicq/Detect-It-Easy/releases/download/Beta/Detect_It_Easy-3.07-x86_64.AppImage
https://github.com/horsicq/Detect-It-Easy/releases/download/Beta/die_3.07_Parrot_5.1_amd64.deb

**Comment by dmknght** [comment]
Gotcha! I think I'll wait for the next release

**Comment by dmknght** [comment]
Thank you a lot! I'm sure Reverse Engineerers will love it :D
