### ISSUE TITLE
Incorrect information reported for Xbox 360 PE32 file

### ISSUE THREAD

**Issue by draiN-NEO** [horsicq/Detect-It-Easy#136]
When scanning a PE32 file for the Xbox 360, DiE will incorrectly report the file as little endian and with the architecture listed as "Unknown" instead of PPC BE. (I don't know if this information affects the detection of compilers/packers but I thought it should be listed as an issue anyway).

![xboxSample](https://user-images.githubusercontent.com/52803804/198395528-c4118f20-e3bd-40d0-b147-38d0e8c8e48d.jpg)

Here is the sample file which shows the issue: 
[sample.zip](https://github.com/horsicq/Detect-It-Easy/files/9883019/sample.zip)

**Comment by horsicq** [comment]
Thanks a lot for the report and the file! I will fix it ASAP

**Comment by horsicq** [comment]
Fixed:

https://github.com/horsicq/Detect-It-Easy/releases/download/Beta/die_win32_portable_3.07.zip
https://github.com/horsicq/Detect-It-Easy/releases/download/Beta/die_win64_portable_3.07.zip
