### ISSUE TITLE
DIE doesn't save its settings on Windows

### ISSUE THREAD

**Issue by arabesc** [horsicq/Detect-It-Easy#138]
I've placed DIE in the "C:\Program Files\" folder on Windows 11 x64, run the app, changed some settings, exited and run app again - the setting were not saved.

**Comment by horsicq** [comment]
Thanks a lot for the testing. It will be fixed.

**Comment by demberto** [comment]
+1, Running DIE as admin fixed it for me.

**Comment by greenozon** [comment]
Maybe this is due to the fact that there is no support yet for Win11 in the code?
eg: https://github.com/horsicq/Formats/blob/329569a4919ac7142feabcd7d718387c3ef50760/xpe.cpp#L11009
