### ISSUE TITLE
diec - how to pass path with spaces?

### ISSUE THREAD

**Issue by matejkac** [horsicq/Detect-It-Easy#146]
Full path: `c:\Program Files (x86)\with space\`
quoting the path usualy works, so 
`diec "c:\Program Files (x86)\with space\"`  should work, but it doesn't.
`diec c:\Progra~2\withsp~1` works, but you have to know the short (8.3)  path names.

Any other way to quote the path?

**Comment by adoxa** [comment]
The problem is you're actually escaping the quote: either remove the backslash (`...space"`), add another one (`...space\\"`), or use slashes (`...space/"`).

**Comment by 111STAR** [comment]
HI @horsicq 
I will send example files

**Comment by modz2014** [comment]
diec "c:/Program Files (x86)/with space/"

**Comment by modz2014** [comment]
> Full path: `c:\Program Files (x86)\with space\` quoting the path usualy works, so `diec "c:\Program Files (x86)\with space\"` should work, but it doesn't. `diec c:\Progra~2\withsp~1` works, but you have to know the short (8.3) path names.
> 
> Any other way to quote the path?

diec "c:/Program Files (x86)/with space/"
