### ISSUE TITLE
PortEx as reference.

### ISSUE THREAD

**Issue by MariasStory** [horsicq/Detect-It-Easy#15]
Please check what can be taken over from:
https://github.com/katjahahn/PortEx
I like this one:
![visualized_sample](https://cloud.githubusercontent.com/assets/6576335/15213832/edff303e-1849-11e6-9a1d-861227799a3e.png)

and the anomalies:
https://github.com/katjahahn/PortEx/blob/master/src/main/java/com/github/katjahahn/tools/anomalies/AnomalySubType.java

**Comment by horsicq** [comment]
Thanks! I'll take a look.
