### ISSUE TITLE
DIE infinite loop

### ISSUE THREAD

**Issue by gadix** [horsicq/Detect-It-Easy#153]
DIE 3.08 (and previous versions) remains in an infinite loop analyzing the file MD5 581C1CDE184C2CB8B9CDD05A713090F1.
I don't know how to (private ) share the sample with you

Regards

**Comment by horsicq** [comment]
Thanks a lot for your report! If you have a Telegram you could to send your file to my Bot: @detectiteasy_bot

**Comment by horsicq** [comment]
https://github.com/horsicq/DIE-engine/releases/tag/3.09
