### ISSUE TITLE
Signature syntax highlighting broken with multiple strings

### ISSUE THREAD

**Issue by learn-more** [horsicq/Detect-It-Easy#154]
The syntax highlighting in the signatures window is broken when there are multiple strings on one line,
it will mark everything inbetween the strings as part of the string as well:

![image](https://github.com/horsicq/Detect-It-Easy/assets/610685/c8ccfd2f-b216-44e0-b6b7-d78ddd1b2988)

**Comment by learn-more** [comment]
It might be enough to make the regex non-greedy:
Instead of:
```
rule.pattern = QRegularExpression(QStringLiteral("\".*\""));
```
use:
```
rule.pattern = QRegularExpression(QStringLiteral("\".*?\""));
```

**Comment by horsicq** [comment]
Thanks a lot! It will be fixed. :)

**Comment by horsicq** [comment]
> rule.pattern = QRegularExpression(QStringLiteral("\".*?\""));

It works perfect. Thank you!

**Comment by horsicq** [comment]
Fixed: https://github.com/horsicq/die_widget/commit/ed75efee2c2017fdcb18613090fb9f369ebfc038
