### ISSUE TITLE
HexView - HexView's font rendering is a bit blurry

### ISSUE THREAD

**Issue by lennysec** [horsicq/Detect-It-Easy#176]
Hi horsicq,

I found HexView's font rendering a bit blurry. You can see it from the screenshot below.
<img width="427" alt="hexview" src="https://github.com/horsicq/Detect-It-Easy/assets/10736852/e5f061cf-b042-49e1-8113-8023ecf5091b">

OS version: macOS 14.0
DiE version: 3.08

It may have something to do with `QPixmap` in `XHexView::paintColumn`, but I am not familiar with QT. Could you please investigate and resolve this issue?

Regards

**Comment by horsicq** [comment]
Thank you a lot for the bugreport! I will take a look.

**Comment by lennysec** [comment]
Hi horsicq,

I've created a PR to fix this issue:
https://github.com/horsicq/XHexView/pull/1

I've tested on macOS 14.0. You can see that the text in HexView has become clearer:
<img width="429" alt="hexview2" src="https://github.com/horsicq/Detect-It-Easy/assets/10736852/eb32f4fe-5454-47c9-813a-49a8c29c4417">

Hope it helps.

**Comment by horsicq** [comment]
Thanks a lot!
