### ISSUE TITLE
Winget pls

### ISSUE THREAD

**Issue by HeavySnowJakarta** [horsicq/Detect-It-Easy#177]
I've already added a request to add it to `winget`: https://github.com/microsoft/winget-pkgs/issues/122464

**Comment by horsicq** [comment]
Thank you! 
Yes. Download page is: https://github.com/horsicq/DIE-engine/releases

**Comment by Dragon1573** [comment]
@HeavySnowJakarta This issue can be closed as "Not planned".

According to [Release 3.08](https://github.com/horsicq/DIE-engine/releases/tag/3.08), they only provided **portable installer** for Windows. They are all regarded as "loose executable" by `winget.exe`, which is currently not supported.

If @horsicq can package the application into an installation wizard, it would be nice.

- Wizzard with MSI, MISX, APPX and EXE file extension are supported by `winget.exe`.
- Wix, InnoSetup, NullSoft and Burn are recommended creator for EXE wizard.
- MUST support silent (prefer with progress) install (by default or with a commandline switch) if creating wizard themselves without any well-known creators.

_Originally posted by @Dragon1573 [here](https://github.com/microsoft/winget-pkgs/issues/122464#issuecomment-1759960860)_

**Comment by HeavySnowJakarta** [comment]
Instead, portable applications are accepted, which may be easiest to deal with.

Reference: https://github.com/microsoft/winget-pkgs/issues/122464#issuecomment-1760164847
