### ISSUE TITLE
[Feature Request] Integration with Context Menu

### ISSUE THREAD

**Issue by Chipsum** [horsicq/Detect-It-Easy#193]
Hey,
Not much to say, however, it would be amazing if it integrated with Shell:

![image](https://github.com/horsicq/Detect-It-Easy/assets/37517008/0d96116b-9c7d-4789-b5fb-a74d7a1c03fd)

**Comment by horsicq** [comment]
Hmm. You can run program with admin rights and "add to context" in options

**Comment by Chipsum** [comment]
@horsicq 
Hummm...
Although there are countless methods to accomplish it, I proposed including it as an available feature for lazy persons like me.
