### ISSUE TITLE
Inconsistencies with Amber Packer

### ISSUE THREAD

**Issue by Gorman88** [horsicq/Detect-It-Easy#195]
Noticed some inconsistencies with DiE being able to identify that a packed executable is actually packed when the executable was specifically packed using Amber. It also doesn't seem to be able identify that Amber is the packer being used at all but that is less of an issue for me than being able to ID whether the executable is packed or not.

I ran 12 tests with various Amber packed Windows PEs. 8 came back with positive identifications of the executable being packed, 4 did not. One thing to note is that originally I thought it was the size of the executable that was causing the problem but I ruled that out since it was able to detect strings.exe was packed (approx 320KiB) but not cmd.exe (approx 471KiB).

I used both DiE and NFD engines for testing with no discernible changes between the results of the two. 

Here are some screenshots of GUI results for strings.exe and cmd.exe from both NFD and DiE engines:

![Screenshot 2024-04-05 at 11 26 52 AM](https://github.com/horsicq/Detect-It-Easy/assets/37813914/34414419-9e12-4b1e-968f-ee3af37be035)
![Screenshot 2024-04-05 at 11 26 43 AM](https://github.com/horsicq/Detect-It-Easy/assets/37813914/be898afa-49fa-404c-a2b1-1c32739a16b9)
![Screenshot 2024-04-05 at 11 26 14 AM](https://github.com/horsicq/Detect-It-Easy/assets/37813914/fbbe1f67-fa36-4455-8f10-2fc37b9efa71)
![Screenshot 2024-04-05 at 11 26 02 AM](https://github.com/horsicq/Detect-It-Easy/assets/37813914/3c07a7a2-071f-4d24-8600-b6e64cff67d7)

**Comment by horsicq** [comment]
Hello! Thanks a lot for the report! Could you please share the files? You could send me it to Telegram @horsicq

**Comment by DosX-dev** [comment]
Amber detection added.
