### ISSUE TITLE
Support pyinstaller packer exe with builtin upx compressed

### ISSUE THREAD

**Issue by jindaxia** [horsicq/Detect-It-Easy#196]
Feature request: Add support to dectct pyinstall packed executeble files 
like Exes and Elfs

I think this yara rule will help：

https://github.com/bartblaze/Yara-rules/blob/5f4961049d0d510b11250d5628383398889fc881/rules/generic/PyInstaller.yar

**Comment by jindaxia** [comment]
YES, try to detect this one
https://cowtransfer.com/s/8eb623f5459b41

**Comment by jindaxia** [comment]
> Hello! The PyInstaller (.exe) detection is already in the database. **Do you have samples that are not detected?**
> 
> I will add a version for Linux in the near future. Thank you!

I  think the Linux version has  some texts like "MEIPASS"

**Comment by DosX-dev** [comment]
> YES, try to detect this one
Heuristic analysis of Detect It Easy indicates that the file is packed with modified UPX. Unfortunately, this makes static analysis impossible to determine PyInstaller. You can try to unpack the file yourself and scan the dump

> like Exes and Elfs
PyInstaller detection for Linux added. Please update the database 👌

**Comment by adoxa** [comment]
I only have a sample size of one (which crashes, but maybe that's just me?) but perhaps it could detect `PYZ-00.pyz` near the end of the file.

**Comment by jindaxia** [comment]
https://pyinstaller.org/en/v4.8/usage.html#using-upx

PyInstaller looks for UPX on the execution path or the path specified with the [--upx-dir](https://pyinstaller.org/en/v4.8/usage.html#cmdoption-upx-dir) option. If UPX exists, PyInstaller applies it to the final executable, unless the [--noupx](https://pyinstaller.org/en/v4.8/usage.html#cmdoption-noupx) option was given. UPX has been used with PyInstaller output often, usually with no problems.

**Comment by jindaxia** [comment]
https://github.com/pyinstxtractor/pyinstxtractor-ng/blob/09eb74bcbb3f443401babbaf94629714b58c543e/pyinstxtractor-ng.py#L52    

I think this magic number helps
    MAGIC = b"MEI\014\013\012\013\016"  # Magic number which identifies pyinstaller

**Comment by DosX-dev** [comment]
> pyinstall packed executeble files

Done. ([click](https://github.com/horsicq/Detect-It-Easy/commit/3e6b84beb2172c7e8dc3cc8a7e480c3764224d5f#diff-e2d46726c13c890957d9e697cd46c096b87c682fd8b741e4193d576eaeed4d7c))
