### ISSUE TITLE
.bss section on Linux it's showing data from next sections

### ISSUE THREAD

**Issue by tttony** [horsicq/Detect-It-Easy#202]
System: Debian 12
DIE version: [3.09](https://github.com/horsicq/DIE-engine/releases/download/3.09/die_3.09_Debian_12_amd64.deb) 

Just picking any executable file with .bss section and it's shows data from the next sections

[Debian.webm](https://github.com/horsicq/Detect-It-Easy/assets/219885/4317a6a7-17c5-4811-ac6d-2c236518fa1f)

On Windows it does not shows any data, even the .bss section is present and it says zero in `SizeOfRawData` (tested only on two executables)  but it would be cool since it just zero initialized bytes to just show the size in bytes? without the need to open the Section Header window to see how many bytes are there

Also it would be better if the section name was showed in the first column like in Windows

**Comment by horsicq** [comment]
Thanks a lot for the bugreport! It will be fixed!
