### ISSUE TITLE
File no more detected as obfuscated since the new beta 

### ISSUE THREAD

**Issue by Porygon31** [horsicq/Detect-It-Easy#216]
Hi,
Since the new beta released (27/06/2024), I have one file that was detected as obfuscated by DiE and that now is no more detected by the new DiE beta release 

![2024-07-01_010955](https://github.com/horsicq/Detect-It-Easy/assets/85462132/24d3416e-cf97-416b-bf75-98578dbf0518)

I don't know whether it's normal or not, at least now he detected that the program was indeed written in VB.NET and not C#

Thanks,
Kind regards,

_Porygon_

**Comment by DosX-dev** [comment]
Hello! Thank you for the report. But we have already fixed this. Can you please update the beta?

**Comment by DosX-dev** [comment]
Hello! The latest version of the beta is working properly. The obfuscation false detection bug was due to incorrect functionality of the DiE Engine standard library.

**Comment by Porygon31** [comment]
> Hello! The latest version of the beta is working properly. The obfuscation false detection bug was due to incorrect functionality of the DiE Engine standard library.

So everything is working perfectly ?

**Comment by DosX-dev** [comment]
Yeah!
