### ISSUE TITLE
Signature Support: Native AoT-compiled .NET Applications

### ISSUE THREAD

**Issue by Still34** [horsicq/Detect-It-Easy#218]
## Summary

Starting from .NET 7, it is now possible to compile .NET applications as Ahead-of-Time-compiled native application - i.e., unmanaged code.
This addition is currently not recognized or picked up by DiE's signatures and *somewhat* incorrectly identifies the binary as standard C++-compiled application.

![image](https://github.com/horsicq/Detect-It-Easy/assets/5843208/297fd620-a407-43d2-b2ea-aa3624a79b6c)

## References
https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/

**Comment by DosX-dev** [comment]
Hello, AOT support has already been partially added. Update to the latest beta

**Comment by Still34** [comment]
Oops - sorry, didn't think to check the beta first. Can confirm it's working.
