### ISSUE TITLE
making a python api module

### ISSUE THREAD

**Issue by talskopas** [horsicq/Detect-It-Easy#219]
Hey,
Is it possible to make a python module, so we can use its API to find attributes from DIE?
something like:

import detectiteasy as die
type = die.find_type(path_to_file)
print(type) # PE32
hash = die.entropy(path_to_file)
print(hash) # ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad

thank you

**Comment by horsicq** [comment]
Hello! Did you see this project:
https://github.com/elastic/die-python
