### ISSUE TITLE
Request : Download db

### ISSUE THREAD

**Issue by dforce** [horsicq/Detect-It-Easy#220]
Is there a possibility to only download the db directory because I want to use this db within another program ?

Thanks

**Comment by horsicq** [comment]
Sure. You could use the db where you want

**Comment by dforce** [comment]
Thanks, but what I want is a download link so I can only download the full db directory instead of downloading the full repository and then extract only the db directory.

Btw : great program

**Comment by horsicq** [comment]
You should check this link: https://stackoverflow.com/questions/7106012/download-a-single-folder-or-directory-from-a-github-repository

**Comment by DosX-dev** [comment]
This entire repository is basically a database. You'll first have to download the entire repository and then get this directory

**Comment by dforce** [comment]
Ok, thanks
