### ISSUE TITLE
Directory scan with filter for filetype

### ISSUE THREAD

**Issue by SIRprise** [horsicq/Detect-It-Easy#236]
Hi,
I would like to search for dotnet exe-files. Is there a way to set a filter at least to *.exe in directory scan? Is there a way to add a Ctrl+F Search?)
(and what is the difference between "subfolder" and "recursive scan", cause "subfolder" seems to search recursive?)

**Comment by DosX-dev** [comment]
Use [https://github.com/horsicq/DIE-sort](https://github.com/horsicq/DIE-sort)

**Comment by SIRprise** [comment]
Hmm, yes, thats slow but it works, thanks. But next time I think I will simply copy all exe-files and than scan it.

**Comment by horsicq** [comment]
I will add the filter.

**Comment by DosX-dev** [comment]
> and what is the difference between "subfolder" and "recursive scan", cause "subfolder" seems to search recursive
Recursive scanning is a type of scan in which a binary file is read multiple times. It has nothing to do with the way you work with the file system
