### ISSUE TITLE
PureBasic possibly not recognized correctly

### ISSUE THREAD

**Issue by SIRprise** [horsicq/Detect-It-Easy#237]
A minor issue...

PB uses POLink by default (Linker from PellesC), but it can also use VC. Now it can also use an ASM or a C Compiler and that is not the MS C one. You can check it with [https://github.com/jacdelad/PureMondrian/releases](https://github.com/jacdelad/PureMondrian/releases) + they link with other DLLs now: [https://www.purebasic.fr/blog/?p=538](https://www.purebasic.fr/blog/?p=538)
If you test Mondian.exe: Ignore warnings from Windows Defender AV... it is every time a false positive.

That was the recognition of DIE:
![grafik](https://github.com/user-attachments/assets/33cc2d55-d442-4136-9188-0d931006186d)

**Comment by DosX-dev** [comment]
Hello, thank you!
