### ISSUE TITLE
Recognize files compiled by FreeBasic compiler 

### ISSUE THREAD

**Issue by ags1234** [horsicq/Detect-It-Easy#241]
DIE does not recognize a FreeBasic compiled exe.

The source of a hello world example file from FreeBasic compiler:
[hello.bas.txt](https://github.com/user-attachments/files/17611395/hello.bas.txt)

Exe compiled with FreeBasic compiler:
[hello.exe.txt](https://github.com/user-attachments/files/17611399/hello.exe.txt)

![2024-11-03_193806](https://github.com/user-attachments/assets/6fe4b76f-f3e7-48f1-a173-3cbbddb1a669)

**Comment by DosX-dev** [comment]
[Done](https://github.com/horsicq/Detect-It-Easy/commit/bb7f1e29148b6d78148b552a510529c8ecf4b97e)
