### ISSUE TITLE
Fix scaling issues for high-DPI devices

### ISSUE THREAD

**Issue by ALXIMIKS** [horsicq/Detect-It-Easy#32]
Provide adaptive program scaling based on user's DPI.

Screenshot from 4k monitor with 175% scaling:
![image](https://user-images.githubusercontent.com/37275503/37419551-69bbcb40-27bd-11e8-91ed-826a299d324e.png)

**Comment by ALXIMIKS** [comment]
Possible work-around is to use the Compatibility:
- activate "Override high DPI scaling behavior";
- set "Scaling performed by" to "System".

![image](https://user-images.githubusercontent.com/37275503/37422430-c67f6750-27c3-11e8-8ed6-e201e786a919.png)

Result:
![image](https://user-images.githubusercontent.com/37275503/37422473-da436610-27c3-11e8-8457-140420b6588e.png)

**Comment by techbliss** [comment]
To fix for all QT apps , since you most likely have trouble with other apps also.
in user variable and not system variable

`QT_AUTO_SCREEN_SCALE_FACTOR=2`
