### ISSUE TITLE
Windows info

### ISSUE THREAD

**Issue by adoxa** [horsicq/Detect-It-Easy#38]
Windows should use UTF-8 to read/display the info.

**Comment by horsicq** [comment]
It will be in the next version of DiE(2.03)

**Comment by horsicq** [comment]
Completed

**Comment by adoxa** [comment]
I don't know if adding the BOM is the right approach (AIUI Linux and macOS actively discourage the BOM). I was thinking something more along the lines of `fromUtf8`.

**Comment by horsicq** [comment]
Ok. I'll add fromUtf8 and revert the changes in the info files.
