### ISSUE TITLE
Info files

### ISSUE THREAD

**Issue by adoxa** [horsicq/Detect-It-Easy#39]
The info files are a mixture of long and short lines. I see three options:

1. Hard wrap everything to 60 columns.
2. Hard wrap nothing, joining lines to make single-line paragraphs (and blank line between).
3. Make use of rich text and use `<p>`.

**Comment by horsicq** [comment]
I think the second option is the best one.

**Comment by adoxa** [comment]
Done.

**Comment by horsicq** [comment]
Thanks a lot!
