### ISSUE TITLE
Testing DIE against a DOS executables collection

### ISSUE THREAD

**Issue by bleuge** [horsicq/Detect-It-Easy#41]
I am testing lastest version against a collection of executable tools, only DOS, I've been doing last years, packers, cryptors, scene stuff, etc, around 29.000 files. Mixed files, I simply uncompressed tons of files, but 7.200 executables. 

A directory scan works ok. I'll check now the results and report, if you are still interested in DOS :D 
But, a directory scan with "show errors" option marked, hangs the program, around the file 10.000, so 50%... Maybe you want to check this.
Thanks you very much, DIE is the best program in its kind!

**Comment by horsicq** [comment]
Thanks a lot for testing DiE. 
Sure we are still interesting in DOS. Could you send me a link to your DOS collection on horsicq@gmail.com?

**Comment by bleuge** [comment]
Email sent.

**Comment by horsicq** [comment]
Thanks!
