### ISSUE TITLE
Regex engine documentation

### ISSUE THREAD

**Issue by Solumnant** [horsicq/Detect-It-Easy#42]
Going through the signature files, I've come across byte matching regex with the normal '.' symbol, but also '$' symbols.

Normally the $ denotes EOS, but in this case there are just a bunch of them strung together, making it look like they might be optional wildcards, and the '.' symbols non-optional wildcards. 

Clarification would be appreciated.

Link illustrates the issue:
https://github.com/horsicq/Detect-It-Easy/blob/master/db/PE/AutoPlay%20Media%20Studio.1.sg

**Comment by horsicq** [comment]
It is for **relative** jumps or calls 

For example: PE.compareEP("e8$$$$$$$$8b")

1) DiE reads 1 BYTE on EntryPoint
2) DiE compares this byte with "e8"
3) **DiE reads 1 DWORD  on EntryPoint+1**
4) DiE goes to (EntryPoint+1+4)+this DWORD
5) DiE read 1 Byte on the new address
6) DiE compares this byte with "8b"
...

There are also:
$$$$$$$$$$$$$$$$ QWORD 
$$$$$ WORD
$$ BYTE

As I said '$' is for relative addresses

For absolute addresses is '#'

$$$$$$$$$$$$$$$$ QWORD 
$$$$$$$$$$$ DWORD
$$$$$ WORD
$$ BYTE

C++ implementation:
DiE: https://github.com/horsicq/DIE-engine/blob/master/binary.cpp#L1348
NFD: https://github.com/horsicq/Formats/blob/master/xbinary.cpp#L2555

**Comment by Solumnant** [comment]
Thank you, I was trying to determine whether your signatures could be ported into YARA, but it appears that isn't the case.
