### ISSUE TITLE
Several alerts are raised by VirusTotal on the version 2.0.4

### ISSUE THREAD

**Issue by chtof** [horsicq/Detect-It-Easy#43]
Hi,

https://www.virustotal.com raised several alerts when scanning "die_win32_portable_2.04.zip".
What is your opinion?

**Comment by horsicq** [comment]
Detect It Easy is open source software.  You could try to build DiE from sources. Here is the tutorial:  http://n10info.blogspot.com/2019/06/build-detect-it-easy-on-linux-windows.html

I guess there are the virus alerts because DiE has been packed with UPX: https://upx.github.io/

**Comment by loll3r0** [comment]
Virustotal shit ahahha

Il giorno mar 9 lug 2019 alle ore 21:00 Hors <notifications@github.com> ha
scritto:

**Comment by horsicq** [comment]
No UPX Version:
https://github.com/horsicq/DIE-engine/releases/tag/2.05
