### ISSUE TITLE
.sig function definitions

### ISSUE THREAD

**Issue by Solumnant** [horsicq/Detect-It-Easy#44]
I've been going through the .sig files and I've noticed that they use a number of functions that I can't find definitions/ source code for in the repository, just auto-complete and help files.

Specifically, when I search for pe.isPEPlus or pe.isNET I see many usages, but no source code.

Where can I find the source code that defines the PE class?

**Comment by horsicq** [comment]
There are only the signatures in this repository. 
Here is the sources of DiE: https://github.com/horsicq/DIE-engine 
How to build DiE from sources: http://n10info.blogspot.com/2019/06/build-detect-it-easy-on-linux-windows.html

pe.isPEPlus: https://github.com/horsicq/DIE-engine/blob/master/die_source/scriptpe.cpp#L741
pe.isNET: https://github.com/horsicq/DIE-engine/blob/master/die_source/scriptpe.cpp#L636

**Comment by Solumnant** [comment]
Thank you, I appreciate it.

Thank you for your help with my other issues too.
