### ISSUE TITLE
Feature requst: Output diec output in JSON format

### ISSUE THREAD

**Issue by securisec** [horsicq/Detect-It-Easy#46]
I am not sure if there are any other ways to output data from diec, but it would be awesome if it could dump it in other formats like JSON.

**Comment by horsicq** [comment]
Good idea. Thanks. I ll add it to my TODO list.
BTW take a look to my another project NFD. It has a console version too and NFD can output to XML format. https://github.com/horsicq/Nauz-File-Detector

**Comment by securisec** [comment]
Awesome! Didnt know about this second project. Love DIE btw! Looking forward to future updates (hopefully with the JSON)

**Comment by horsicq** [comment]
https://github.com/horsicq/DIE-engine/releases/tag/2.05
