### ISSUE TITLE
[Question] Entropy threshold

### ISSUE THREAD

**Issue by packmad** [horsicq/Detect-It-Easy#48]
What is the entropy threshold above which an executable is considered packed?
Where did you get that number?

FYI 
[Manalyze](https://github.com/JusticeRage/Manalyze/blob/master/plugins/plugin_packer_detection.cpp) consider high entropy above 7.0

**Comment by adoxa** [comment]
Have a look at [this](http://n10info.blogspot.com/2014/06/entropy-and-distinctive-signs-of-packed.html) (and the article linked at the bottom).

**Comment by packmad** [comment]
@adoxa your link does not answer my question, probably because I was not precise:

What is the entropy threshold above which Detect-It-Easy considers an executable packed?

**Comment by horsicq** [comment]
Hello, 
In the **Manalyze**, heuristic analysis is performed. The program compares the names of known sections from the list and calculates the entropy if a match is found. Unfortunately, it is difficult to call such a method very accurate.
**DiE** uses signatures for each specific packer / Protector.
The article cited by **Adoha** details how entropy is calculated. If we take the maximum entropy as 8.0, then values ​​greater than **6.5-7.0** can be considered conditionally signs that the code is "packed". **There are no exact values ​​and cannot be**. This is empirical evidence.

**Comment by packmad** [comment]
I'm sorry, again there is a misunderstanding.

![Selection_002](https://user-images.githubusercontent.com/5713555/69560501-25ba9d80-0fac-11ea-8cca-12eb3351c620.png)

![Selection_003](https://user-images.githubusercontent.com/5713555/69560517-29e6bb00-0fac-11ea-973a-506231ae149e.png)

Long story short: what's the logic behind "packed" or "not packed"?
In Detect-It-Easy code there is something like:
```
if entropy > threshold: display("packed")
else: display("not packed")
```

**Comment by horsicq** [comment]
Ok. You could change  the threshold in the  Options -> Entropy -> Threshold.
**Default value is 7.0**

The logic is here:
https://github.com/horsicq/DIE-engine/blob/master/die_source/gui_source/dialogentropy.cpp#L588

Source code for GUI is here: https://github.com/horsicq/DIE-engine

How to build DiE from Sources: http://n10info.blogspot.com/2019/06/build-detect-it-easy-on-linux-windows.html

**Comment by packmad** [comment]
Awesome! Thank you very much and congrats on your project!

**Comment by packmad** [comment]
Awesome! Thank you very much and congrats on your project!

**Comment by packmad** [comment]
FYI my question was related to this work: 
https://blog.talosintelligence.com/2020/02/new-research-paper-prevalence-and.html

**Comment by horsicq** [comment]
Thanks a lot! This work is very interesting.

**Comment by packmad** [comment]
I forgot to tell you the most important takeaway for you from this work (I'm one of the authors).
I quote:

> Probably because of its finely tuned signatures, DIE detects no well-known packer in our entire dataset. This is not a bad result, as we expect the vast majority of samples in our dataset to rely on custom packing routines. In fact, popular off-the-shelf packers are widely known and easily recognizable, thus making it more unlikely for them to ‘fly under the radar’, which is the main advantage of adopting a custom low-entropy scheme.
In contrast, both PEiD and Manalyze generated a large number of alerts [...]

So congrats and keep up the good work! Bye.
