### ISSUE TITLE
Option to provide a single diec.exe executable?

### ISSUE THREAD

**Issue by ferventcoder** [horsicq/Detect-It-Easy#5]
I noticed that diec.exe has a few dlls it depends on. Is there a way to merge those files into diec.exe so that they are not necessary? 

Other than that, I am blown away at how awesome and fast this is.

**Comment by horsicq** [comment]
Yes. Just need Qt with static libraries for diec's sources. https://github.com/horsicq/DIE-engine

How to statically link Qt 4: http://www.formortals.com/how-to-statically-link-qt-4

Also there are tools like "VMware ThinApp" http://www.vmware.com/products/thinapp to merge all dlls and exes to one big file.

**Comment by whythisnamebusy** [comment]
or use **Enigma Virtual Box** 

[http://www.enigmaprotector.com/en/downloads.html](link)
