### ISSUE TITLE
Are there any documentation about signature script syntax?

### ISSUE THREAD

**Issue by whc2001** [horsicq/Detect-It-Easy#52]
I am trying to add a new signature to DIE, but I didn't found any documentation about the syntax of the script and the list of functions I can use. Are there any instructions?

**Comment by horsicq** [comment]
Hello, https://github.com/horsicq/DIE-engine/releases/download/1.01/DIE_1.01_win.zip 
Folder "SDK"

**Comment by whc2001** [comment]
Thanks!
