### ISSUE TITLE
Need help understanding source of bytepattern signature for .Net Reactor

### ISSUE THREAD

**Issue by JeremyWildsmith** [horsicq/Detect-It-Easy#53]
Hello,

Is someone here able to help me understand where the source or reason is behind the bytepatten in the .Net Reactor signature?

I am referring specifically to this pattern:
````
5266686E204D182276B5331112330C6D0A204D18229EA129611C76B505190158
````

Thanks!

Jeremy Wildsmith

**Comment by horsicq** [comment]
Hello, it's just a signature from  protected files(.Net Reactor 4.8-4.9). If you need examples with this signature I could send you  the files.
DiE has signatures from many contributors, Let us know if you have another ideas how to detect .Net Reactor.

**Comment by JeremyWildsmith** [comment]
Hello,

Thank you very much for you response.

I am looking into how these samples are detected and looking at that byte-pattern I can't associate it to anything meaningful in the PE or .Net Assembly. Ie no file structure.

My guess at this point is that it is just used by reactor to mark the file some how. Maybe for licensing purposes?

I was just curious if anyone knew the significance of those bytes.

Thanks!
