### ISSUE TITLE
String limit

### ISSUE THREAD

**Issue by Kebechet** [horsicq/Detect-It-Easy#58]
Would or is possible to get rid of maximal 10k string limit in string-search ?

**Comment by horsicq** [comment]
Yes. The next version of DiE wil be have this feature.

**Comment by Kebechet** [comment]
Great to hear that. And do u think that would be possible to catche results of string searches ?
Because for example when you search Unicode strings...then all ASCII strings...and after that you will come back to unicode...you have press SEARCH again. Could you preserve results of already scanned types of strings ? I think it would be very helpful.

**Comment by horsicq** [comment]
Good idea. :) I made it already.

![image](https://user-images.githubusercontent.com/7762949/80310677-421d6900-87dc-11ea-8037-ec57ddd0977c.png)

It will be in the next version of DiE

**Comment by Kebechet** [comment]
You are amazing ! When do u plan to release it ?
I sent you some beer-money 🍻 😄 
Keep up the good work !

**Comment by horsicq** [comment]
Thank you! I'll release it in 1-2 months.

**Comment by horsicq** [comment]
The next version will be 3.00(not 2.07). So I need a bit more time. :)

**Comment by Kebechet** [comment]
Thank you for letting me know ❤
Do you have some estimated release date ?

**Comment by horsicq** [comment]
I want to make release on 01.07.2020
