### ISSUE TITLE
Chinese Simplified translation problem

### ISSUE THREAD

**Issue by wbsdty331** [horsicq/Detect-It-Easy#6]
Hello,

I found there is some part of your translation is missing and it is imcomplete I will fix it and make some improvement. 
When I am done, I will upload New Files.

Thanks :)

**Comment by horsicq** [comment]
Thanks a lot!

**Comment by wbsdty331** [comment]
https://drive.google.com/file/d/0B9Qm978p4Cb2c0ZKQmlxMmhIT0E/view?usp=sharing

But I didn't found these String in QT Language List.
![qq 20160101192026](https://cloud.githubusercontent.com/assets/4280572/12070636/de06e1e4-b0bc-11e5-920a-94b0e9695329.png)
![qq 20160101192009](https://cloud.githubusercontent.com/assets/4280572/12070637/de09b1a8-b0bc-11e5-8ce4-e597a9ad5eea.png)

**Comment by hypn0chka** [comment]
No need to translate "packer/library/compiler etc.". It's a special strings from signatures' files. If you translate it, Detect It Easy can't found signatures.

**Comment by wbsdty331** [comment]
@hypn0chka OK

**Comment by horsicq** [comment]
Thanks! Could you make *.qph file?

**Comment by wbsdty331** [comment]
@horsicq NOT Just QM File

**Comment by horsicq** [comment]
Hmm. qm is compiled file. Did you use Qt linguist to make it?

**Comment by wbsdty331** [comment]
@horsicq  Yes, I used QT Linguist to translate.

**Comment by horsicq** [comment]
Great! Could you try "save as" -> "Qt linguist 'Phrase book'".
Also not "release as"

**Comment by wbsdty331** [comment]
@horsicq 
`https://drive.google.com/file/d/0B9Qm978p4Cb2YWo4d0tzaWNSamc/view?usp=sharing`

**Comment by horsicq** [comment]
Super! I'll add this translation to the next DiE's release.

**Comment by wbsdty331** [comment]
:+1: 
:laughing:
