### ISSUE TITLE
./base/diec: not found

### ISSUE THREAD

**Issue by ctrlcantoniogodinho** [horsicq/Detect-It-Easy#62]
When diec.sh is called from a directory other than the location where it resides, it fails to run with message ./base/diec: not found. the same happens with die.sh

Example:
 - DIE installed in /lab/tools/die

1. cd into /lab/sandbox
2. execute /lab/tools/die/diec.sh <FILE_NAME>

Results:
./base/diec: not found.

OS: Ubuntu 20.04, bash 5.0.17

FIX (bold):

#!/bin/sh
**CWD=$(dirname $0)**
export LD_LIBRARY_PATH="**$CWD**/base:"
**$CWD**/base/diec $*

**Comment by horsicq** [comment]
Thanks a lot!

**Comment by horsicq** [comment]
https://github.com/horsicq/DIE-engine/releases/tag/3.01
