### ISSUE TITLE
how search a folder or same selected file by diec?

### ISSUE THREAD

**Issue by WillDawnlll** [horsicq/Detect-It-Easy#64]
i remember old version diec (0.9?) can search a folder in once , but when i use 3.0 , cant find some paramater or input mode to search mutl file.....thanks for this tool , should i use old version for this function?

**Comment by horsicq** [comment]
Thanks a lot for the information. I will add this option in the next version. You could still use old version(2.06).

**Comment by WillDawnlll** [comment]
thank u =v=
