### ISSUE TITLE
Blank option for all drop downs in settings

### ISSUE THREAD

**Issue by LelouBil** [horsicq/Detect-It-Easy#65]
When you go in the settings each drop down menu has a blank option, is this normal ?

**Comment by horsicq** [comment]
Yes. Balnk option -> no option. No translation, no style ...

**Comment by LelouBil** [comment]
That's not very intuitive. How can the application have no style or no language ?
That's not a very important thing but I think it would be better to just set defaults instead of empty options.

**Comment by horsicq** [comment]
Ok. I will think about it. "Default" would be nice.

**Comment by horsicq** [comment]
https://github.com/horsicq/DIE-engine/releases/tag/3.01

**Comment by LelouBil** [comment]
Thanks !
