### ISSUE TITLE
Consider publish the app to Microsoft Windows Store

### ISSUE THREAD

**Issue by jingliancui** [horsicq/Detect-It-Easy#67]
ILSPY the decompile tool had been upload to store. Maybe you can do this so developers can download it from store without download from github.

**Comment by horsicq** [comment]
Thanks a lot for the good idea. I'll try to do it in the next version(3.01)

**Comment by jingliancui** [comment]
Thanks , It's convenience to auto update from store when you publish release version of detect-it-easy .😄

**Comment by Ytrog** [comment]
You can also install it using chocolatey: `choco install die -y` see: https://community.chocolatey.org/packages/die

**Comment by DosX-dev** [comment]
The Windows App Store only accepts UWP-based apps. DiE is not UWP.
