### ISSUE TITLE
Please add MIME type and Detection reason

### ISSUE THREAD

**Issue by ibhabc** [horsicq/Detect-It-Easy#68]
Sir/madam, If possible please add an option that will also let us know the MIME type,
Please see:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types
https://htmlstrip.com/mime-file-type-checker

And also add detection reason from which I get know at which point and what signature its linker or compiler or language get detected.
Thanks, for my virus analysis, my first step is Detect it easy.
So it will be more easy for me if you add these 2 features. It will prevent me to go anywhere for findings and searching and wasting time.

**Comment by horsicq** [comment]
Thanks a lot for the good idea! I'll try to add the MIME type detection in the next version of DiE(3.01)

You could see the signature if you click on "S"

![image](https://user-images.githubusercontent.com/7762949/92217774-7266c980-ee98-11ea-9b29-cfee27ebf4b6.png)

**Comment by ibhabc** [comment]
Oh wow !
I wonder how you have collected these a lots of signatures ?
There are alot of signatures in C++

**Comment by ibhabc** [comment]
For finding MIME type in c#, you can use
```csharp
string contentType = MimeMapping.GetMimeMapping("someFileName.pdf")
// contentType = "application/pdf"
```
 https://stackoverflow.com/a/23373189/11390822

There may be also an alternative approach in c++.

**Comment by horsicq** [comment]
Thanks! I want to take all MIME types from here: https://www.iana.org/assignments/media-types/media-types.xml

**Comment by bitraid** [comment]
> Thanks! I want to take all MIME types from here: https://www.iana.org/assignments/media-types/media-types.xml

Aren't QT5 libraries (QMimeType, QMimeDatabase) good enough?

**Comment by horsicq** [comment]
> Aren't QT5 libraries (QMimeType, QMimeDatabase) good enough?

May be that will be enough. Moreover, QMimeDatabase uses an external xml file as its database. This file can be expanded

**Comment by ibhabc** [comment]
Sorry for my mistake here.
That library only gets MIME type from file extension.
So its not good idea. We should find a way to get MIME type from data NOT file extension. Because anyone can fool DIE with extension.

**Comment by horsicq** [comment]
Sure. It will be MIME Type detections from data not extension.

**Comment by ibhabc** [comment]
Yeah that what I wanted. 
Now also I have got working code in java. Java is cross-platform and can be use anywhere.
I have an pic and I change its extension to txt. But even I get correct result.
On cmd 
```bash
javac MyClass.java & java MyClass
//image/jpeg
```

**MyClass.java**
```java
import java.io.IOException;
import java.io.*;
import java.io.InputStream;
import javax.activation.MimetypesFileTypeMap;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.List;
import java.net.HttpURLConnection;
import java.net.URL;
import java.net.URLConnection;
import java.util.Map;

public class MyClass 
{
    public static void main(String[] args) 
    {
        try 
        {
            byte[] content = Files.readAllBytes(Paths.get("abc.txt"));
            InputStream is = new BufferedInputStream(new ByteArrayInputStream(content));
            String mimeType = URLConnection.guessContentTypeFromStream(is);
            System.out.println(mimeType);
        }
        catch (Exception ex) 
        {
        }
    }
}
```

**Comment by ibhabc** [comment]
In windows there is system32 dll named urlmon.dll which can be used to detect mime,
Please see full working code here https://github.com/ibhabc/detect_mimetype.net
```csharp
using System;

namespace MIME {

  public class Detect {

    [System.Runtime.InteropServices.DllImport(@"urlmon.dll", CharSet = System.Runtime.InteropServices.CharSet.Auto)]
    private extern static uint FindMimeFromData(
    uint pBC, [System.Runtime.InteropServices.MarshalAs(System.Runtime.InteropServices.UnmanagedType.LPStr)] System.String pwzUrl, [System.Runtime.InteropServices.MarshalAs(System.Runtime.InteropServices.UnmanagedType.LPArray)] byte[] pBuffer, uint cbSize, [System.Runtime.InteropServices.MarshalAs(System.Runtime.InteropServices.UnmanagedType.LPStr)] System.String pwzMimeProposed, uint dwMimeFlags, out uint ppwzMimeOut, uint dwReserverd);

    public static string FromFile(string filepath) {
      if (!System.IO.File.Exists(filepath)) {
        return filepath + " not found";
      }
      byte[] buffer = new byte[256];
      using(System.IO.FileStream fs = new System.IO.FileStream(filepath, System.IO.FileMode.Open)) {
        if (fs.Length >= 256) fs.Read(buffer, 0, 256);
        else fs.Read(buffer, 0, (int) fs.Length);
      }

      FindMimeFromData(0, null, buffer, 256, null, 0, out uint mimetype, 0);
      IntPtr mimeTypePtr = new IntPtr(mimetype);
      string mime = System.Runtime.InteropServices.Marshal.PtrToStringUni(mimeTypePtr);
      System.Runtime.InteropServices.Marshal.FreeCoTaskMem(mimeTypePtr);
      return mime;
    }

  }
}
```

**Comment by horsicq** [comment]
Thanks but we need a solution for Linux and Mac too.

**Comment by ibhabc** [comment]
yes right. I am also trying to find for that too.

**Comment by ibhabc** [comment]
I see a new thing, 
It is independent of any lib and you can easily read the concept and easily convert it to c++ signature.
Please see 
https://github.com/Muraad/Mime-Detective/blob/master/MimeDetective/MimeTypes.cs

**Comment by ibhabc** [comment]
You can grab signatures from here
https://www.garykessler.net/library/file_sigs.html
https://github.com/gabriel-vasile/mimetype/tree/master/internal/matchers

**Comment by horsicq** [comment]
Thanks. I will take a look!

**Comment by ibhabc** [comment]
Sorry again. Previous lib is not stable and have some less signatures. So will be expensive to arrange that.
Did you see that ? https://superuser.com/a/274737/1119561
There is an lib called TrID which has a lot of signatures.
and also implemented in many languages(AutoIt, C#, C++, Delphi, FreeBASIC, PowerBASIC, PureBASIC, Python, thinBasic, VB.NET, VB6)
See samples here. Also C++ included in that.
https://mark0.net/code-tridlib-e.html

**Comment by horsicq** [comment]
Thanks. We have now all the inforamtion we need.

**Comment by ibhabc** [comment]
Okay then load and fire it. :1st_place_medal: 

From my ant research, **I guess TrIDEngine isn't open source** but samples using it are simple and quite better.
So thats mean **it can be use in other platforms as well.** 
But I don't know much about QT.

By the way, **do you recommend QT as cross platform** ?
I have used Xamarin-Forms but **it is just cross-platform**, And here what I get:
--Xamarin build time is slow
--There build binary has huge file size and memory consumption.

**Comment by horsicq** [comment]
> By the way, **do you recommend QT as cross platform** ?
> I have used Xamarin-Forms but **it is just cross-platform**, And here what I get:
> --Xamarin build time is slow
> --There build binary has huge file size and memory consumption.

Take Qt if you need Desktop apps( Windows/Linux/OSX). 
Take Xamarin if you need Mobile apps (Android/iOS).

There are Qt for Mobile apps and Xamarin for Desktop apps but These are not so good.

**Comment by ibhabc** [comment]
You can share stable updates with me. I will surely coporate with you. Thanks again.

**Comment by horsicq** [comment]
https://github.com/horsicq/DIE-engine/releases/tag/3.01
