### ISSUE TITLE
XVolkolak bug reporting

### ISSUE THREAD

**Issue by ryanmkurtz** [horsicq/Detect-It-Easy#70]
Sorry this doesn't have anything to do with Detect-It-Easy, but I wanted to report a bug in XVolkolak and I couldn't find where to do that.  Can you point me in the right direction?

Thanks!

**Comment by horsicq** [comment]
Hello Ryan! I will make XVolkolak Open source and create a repo for bugreports. But now I make another projects. :(
What problem do you have with XVolkolak?

**Comment by ryanmkurtz** [comment]
It's a very minor issue, but on line 3 of `xvlkc.sh`, there needs to be a `$*` so the arguments get passed through.

Thanks!

**Comment by horsicq** [comment]
Thanks!
