### ISSUE TITLE
MoleBox.2.sg causes a Parse error on execution

### ISSUE THREAD

**Issue by 3ster** [horsicq/Detect-It-Easy#73]
`./diec` throws error `MoleBox.2.sg: 51: SyntaxError: Parse error` after printing linker information.
Possibly related to [commit 0bc96b5](https://github.com/horsicq/Detect-It-Easy/commit/0bc96b5d3a513969c986ca22aefb77f1655e9ae4); can be suppressed (or fixed?) by reverting this change.

**Comment by horsicq** [comment]
Thanks a lot for the bugreport! I has ben fixed. https://github.com/horsicq/Detect-It-Easy/commit/630d29750a8c39d5f72347462eb4152ec0a0afa6
