### ISSUE TITLE
Disable WOW64 file system redirection

### ISSUE THREAD

**Issue by seiren-naru-shirayuri** [horsicq/Detect-It-Easy#74]
Because Die is a 32-bit application, WOW64 filesystem redirection may cause trouble when opening a file under System32.

The easiest way to fix this bug is to access %SystemRoot%\sysnative instead of %SystemRoot%\system32 on 64-bit Windows.

**Comment by horsicq** [comment]
Thanks a lot for the bugreport. The next versions of DiE will be 32-bit and 64-bit.

**Comment by horsicq** [comment]
https://github.com/horsicq/DIE-engine/releases/tag/3.01
