### ISSUE TITLE
[ERROR] Qt5 cannot be found

### ISSUE THREAD

**Issue by hectongh** [horsicq/Detect-It-Easy#75]
1.When I type "die" in a shell and press enter,the system show me "./base/die: ./base/libQt5Core.so.5: version `Qt_5.15' not found (required by /usr/lib/libQt5OpenGL.so.5)",but I have the Qt.5.15.1 on my computer.
2.system info
    ->which qmake
    /usr/bin/qmake
    ->qmake -version
    QMake version 3.1
    Using Qt version 5.15.1 in /usr/lib
How to fix it?

**Comment by horsicq** [comment]
Thanks a lot for the bugreport! Do you use DiE from bundle or did you compile it from sources?

**Comment by horsicq** [comment]
Is diec working? diec is a console version.

**Comment by hectongh** [comment]
> I fixed this issue: [horsicq/DIE-engine@20a4a44](https://github.com/horsicq/DIE-engine/commit/20a4a440eb80b7e9bc41959e0aef11d3b98c45f7)
> Could you try this file? https://github.com/horsicq/DIE-engine/releases/download/3.00/die_lin64_portable_3.00.tar.gz

ok,it's works fine,thanks.
I download this from AUR,maybe there is a problem.
