### ISSUE TITLE
Build DIE with QT 5.15.1

### ISSUE THREAD

**Issue by claudiudc** [horsicq/Detect-It-Easy#76]
I am trying to build DIE engine with QT 5.15
For some reason application crashes when I try to open.
Added this to build file:
set VS_PATH="C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise"
set QT_PATH=C:\Qt\5.15.1\msvc2019
set SEVENZIP_PATH="C:\Program Files\7-Zip"

I've also tried with VS 2019 path.
Have you tried to build DIE with this version of QT? Will this work?

**Comment by horsicq** [comment]
Yes, the version Qt 5.15.1 will work. I created a build script for this version: https://github.com/horsicq/DIE-engine/blob/master/build_win64.bat

**Comment by claudiudc** [comment]
Thank you so much!
