### ISSUE TITLE
R U developer or maintainer of PEID ?

### ISSUE THREAD

**Issue by footballs** [horsicq/Detect-It-Easy#78]

**Comment by horsicq** [comment]
?

**Comment by footballs** [comment]
![Capture](https://user-images.githubusercontent.com/70466231/101137171-362a3d00-3630-11eb-8d1d-41145c399993.PNG)
I got PEid executable s in your detect easy binaries so I inquired whether you are developer/maintainer of PEid ?
So that I may ask question about that.

**Comment by horsicq** [comment]
I am not developer of PEiD. :(
Where did you download this binaries with PEiD?

**Comment by footballs** [comment]
I think I downloaded zip from github releases or website ntinfo.biz .
Not sure about that. Its too old around 2019.July version:2.05.
Okay leave it. I will contact PEiD developers. 
Thank you so much for the time.
Best regards!
