### ISSUE TITLE
Not detecting Eazfuscator

### ISSUE THREAD

**Issue by Faq** [horsicq/Detect-It-Easy#83]
For win users there are only 2 tools like this, so comparing them:
![image](https://user-images.githubusercontent.com/322016/107858025-901e5e80-6e3a-11eb-99e4-2343dbcb3e62.png)

[Used exe here](https://mega.nz/file/WtkAmQAS#o9s50lf6g_ZnpEPDVbYXOgd6KRjH1X5mpOLiq8DgCeE)

**Comment by horsicq** [comment]
Thanks a lot for the bugreport! I will take a look.

**Comment by horsicq** [comment]
Fixed.

https://github.com/horsicq/Detect-It-Easy/commit/55dbd043f1a779e71ebb4eee3bb207bcf3767f33
https://github.com/horsicq/SpecAbstract/commit/443e9205754267137e09d92971c3f19a76a079ad
