### ISSUE TITLE
[Feature request] More friendly compile with Debian packaging

### ISSUE THREAD

**Issue by dmknght** [horsicq/Detect-It-Easy#86]
Hi! I want to pack your tool to Parrot OS using Debian packaging standard and the installation script is too hard to make it. So there are some suggestions:
1. Proper makefile that could be used for all platforms
2. required package name on Linux system
3. Allow compiler use not only shared libraries but libs as well (like `qt5-dev`) or set path to shared library for run time usage

I hope we can work together to improve this.
Best regards!

**Comment by horsicq** [comment]
Thanks a lot for the good idea. I will let you know if I make the suggestions.

**Comment by dmknght** [comment]
For now, i made some changes for the installation script and it worked on Parrot 4.11.1
Scripts:
```
#!/bin/bash -x
QT_PATH=/usr/lib/x86_64-linux-gnu
RELEASE_VERSION=$(cat "release_version.txt")
echo $RELEASE_VERSION
SOURCE_PATH=$PWD

BUILD_NAME=die_engine

cd $SOURCE_PATH

function makeproject
{
    cd $SOURCE_PATH/$1
    
    qmake $1.pro -spec linux-g++
    make -f Makefile clean
    make -f Makefile

    rm -rf Makefile
    rm -rf Makefile.Release
    rm -rf Makefile.Debug
    rm -rf object_script.*     

    cd $SOURCE_PATH
}


makeproject build_libs
makeproject gui_source # sudo apt install qtscript5-dev

makeproject console_source

cd $SOURCE_PATH/gui_source
lupdate gui_source_tr.pro
cd $SOURCE_PATH

mkdir -p $SOURCE_PATH/release
rm -rf $SOURCE_PATH/release/$BUILD_NAME
mkdir -p $SOURCE_PATH/release/$BUILD_NAME
mkdir -p $SOURCE_PATH/release/$BUILD_NAME/base
mkdir -p $SOURCE_PATH/release/$BUILD_NAME/base/platforms

cp -R $SOURCE_PATH/build/release/die                     		$SOURCE_PATH/release/$BUILD_NAME/base/
cp -R $SOURCE_PATH/build/release/diec                     		$SOURCE_PATH/release/$BUILD_NAME/base/

mkdir -p $SOURCE_PATH/release/$BUILD_NAME/base/lang
cp -Rf $SOURCE_PATH/XStyles/qss/ $SOURCE_PATH/release/$BUILD_NAME/base/qss/
cp -Rf $SOURCE_PATH/Detect-It-Easy/info/ $SOURCE_PATH/release/$BUILD_NAME/base/info/
cp -Rf $SOURCE_PATH/Detect-It-Easy/db/ $SOURCE_PATH/release/$BUILD_NAME/base/db/

lrelease  $SOURCE_PATH/gui_source/translation/die_de.ts -qm  $SOURCE_PATH/release/$BUILD_NAME/base/lang/die_de.qm
lrelease  $SOURCE_PATH/gui_source/translation/die_ja.ts -qm  $SOURCE_PATH/release/$BUILD_NAME/base/lang/die_ja.qm
lrelease  $SOURCE_PATH/gui_source/translation/die_pl.ts -qm  $SOURCE_PATH/release/$BUILD_NAME/base/lang/die_pl.qm
lrelease  $SOURCE_PATH/gui_source/translation/die_pt_BR.ts -qm  $SOURCE_PATH/release/$BUILD_NAME/base/lang/die_pt_BR.qm
lrelease  $SOURCE_PATH/gui_source/translation/die_fr.ts -qm  $SOURCE_PATH/release/$BUILD_NAME/base/lang/die_fr.qm
lrelease  $SOURCE_PATH/gui_source/translation/die_ru.ts -qm  $SOURCE_PATH/release/$BUILD_NAME/base/lang/die_ru.qm
lrelease  $SOURCE_PATH/gui_source/translation/die_vi.ts -qm  $SOURCE_PATH/release/$BUILD_NAME/base/lang/die_vi.qm
lrelease  $SOURCE_PATH/gui_source/translation/die_zh.ts -qm  $SOURCE_PATH/release/$BUILD_NAME/base/lang/die_zh.qm
lrelease  $SOURCE_PATH/gui_source/translation/die_zh_TW.ts -qm  $SOURCE_PATH/release/$BUILD_NAME/base/lang/die_zh_TW.qm
lrelease  $SOURCE_PATH/gui_source/translation/die_tr.ts -qm  $SOURCE_PATH/release/$BUILD_NAME/base/lang/die_tr.qm
```
# What changed:
- All libs part was deleted and use the system library for compile time and runtime
- Remove the bash scripts. maintainer can create custom scripts for `die` and `diec`
- Remove making tarball release file since it doesn't need on Debian system.
# Compile time libs and packages. Bash is used to run the bash file and won't need (ofc on any system, it should be default. This is defined for auto build system) if we can use Makefile for this. Maybe define `make` here is needed.
 qtscript5-dev,
 qt5-qmake,
 bash,
 libqt5svg5-dev,
 libqt5opengl5-dev,
 qttools5-dev-tools
# Runtime libs
 libqt5core5a,
 libqt5svg5,
 libqt5gui5,
 libqt5widgets5,
 libqt5opengl5,
 libqt5dbus5,
 libqt5scripttools5,
 libqt5script5,
 libqt5network5,
 libicu67,

Result:
- Build succesfully and run with no error
- The actual package size reduced to 3.3 mb because package no longer needs shared libs in the installtion package. The previous size could be up to > 130mb

**Comment by horsicq** [comment]
Great job! Thank you a lot! I will add this script to my repo.

**Comment by dmknght** [comment]
> Great job! Thank you a lot! I will add this script to my repo.

Well how about create a Makefile? You know this script is based on the `build_linux64`

**Comment by horsicq** [comment]
Yes. I know Makefile. I need some time to create it.

**Comment by horsicq** [comment]
> > Great job! Thank you a lot! I will add this script to my repo.
> 
> Well how about create a Makefile? You know this script is based on the `build_linux64`

Could you try:

Install packages:

- sudo apt-get install qtbase5-dev -y
- sudo apt-get install qtscript5-dev -y
- sudo apt-get install qttools5-dev-tools -y
- sudo apt-get install git -y
- sudo apt-get install build-essential -y

git clone --recursive https://github.com/horsicq/DIE-engine.git

Run build script: bash -x build_dpkg.sh

**Comment by dmknght** [comment]
> > > Great job! Thank you a lot! I will add this script to my repo.
> > 
> > 
> > Well how about create a Makefile? You know this script is based on the `build_linux64`
> 
> Could you try:
> 
> Install packages:
> 
>     * sudo apt-get install qtbase5-dev -y
> 
>     * sudo apt-get install qtscript5-dev -y
> 
>     * sudo apt-get install qttools5-dev-tools -y
> 
>     * sudo apt-get install git -y
> 
>     * sudo apt-get install build-essential -y
> 
> 
> git clone --recursive https://github.com/horsicq/DIE-engine.git
> 
> Run build script: bash -x build_dpkg.sh

The script is good. I'm seeing you are doing the mapping path method? in this case you don't really need sudo for chmod imo because paths are at the non-root directories which will be mapped later.

**Comment by horsicq** [comment]
Ok. I will try without sudo.

**Comment by dmknght** [comment]
> Ok. I will try without sudo.

Well i think no need to try it because that was just for permission and the logic is the same.

**Comment by horsicq** [comment]
Ok. Thanks.

**Comment by horsicq** [comment]
It works now without sudo. 
https://github.com/horsicq/DIE-engine/commit/ecbcb2fc4698e1ba11c6a25ef9cec8b0ac44880f

**Comment by horsicq** [comment]
Ok. I will create Makefile too. :)

**Comment by horsicq** [comment]
Do you write about classic linux compilation?

./configure # it creates Makefile
make # it compiles Makefile
make install # it installs the program

**Comment by dmknght** [comment]
> Do you write about classic linux compilation?

yes that is what i meant :D and it should work for not only Linux but other platforms (and IDE that supports compile from makefile)

**Comment by dmknght** [comment]
Just to update the news: finally `die-engine` arrived Parrot repository. It is on `rolling-testing` repo, upstream name `die-engine` and package name `detect-it-easy`
![image](https://user-images.githubusercontent.com/29118926/117494726-40948e00-af64-11eb-98a7-eb9b6a4d9b03.png)

**Comment by horsicq** [comment]
Looks great. Thanks a lot!

**Comment by horsicq** [comment]
Fixed:

Clone project: git clone --recursive https://github.com/horsicq/DIE-engine.git

- chmod a+x configure
- ./configure
- make
- make install

Could also  make configure from configure.ac. Need autoconf

autoreconf -i
