### ISSUE TITLE
Shortcuts dialog

### ISSUE THREAD

**Issue by zeitbit** [horsicq/Detect-It-Easy#88]
Hi,
There is a little problem with the buttons of "Shortcuts" dialog; the "Clear" button does not clear the selected shortcut and the buttons "OK" and "Cancel" don't close the dialog and any change in the shortcuts is always saved.
Cheers!

DIE v3.02
Windows 10 Pro 20H2

**Comment by horsicq** [comment]
Thanks you a lot for the bugreport! I will take a look,

**Comment by diassynthesis** [comment]
Hi, 
same problem on Windows 7 SP1.
best regards.

**Comment by horsicq** [comment]
https://github.com/horsicq/DIE-engine/releases/tag/3.03b
