### ISSUE TITLE
Detection of pyinstaller

### ISSUE THREAD

**Issue by YoavLevi** [horsicq/Detect-It-Easy#89]
Currently, there is no detection of pyinstaller binaries (e.g, https://github.com/AlessandroZ/LaZagne).
It seems like they all have the same static properties:
![image](https://user-images.githubusercontent.com/60928603/126393146-b314bf19-b7da-4467-88e2-834aa0e5354a.png)
and high entropy.
Is it possible to add a signature for those binaries? (which are very common)
Thanks.

**Comment by horsicq** [comment]
Thanks a lot for the bugreport. I will take a look.

**Comment by horsicq** [comment]
Fixed:

https://github.com/horsicq/Detect-It-Easy/commit/1a326c0dec132306f7f9eba255abe611a14d7436
