### ISSUE TITLE
Console - Specifying a full path for database returns "Invalid database name: c"

### ISSUE THREAD

**Issue by ferventcoder** [horsicq/Detect-It-Easy#9]
~~~sh
C:\>diec.exe "C:\Temp\FileZilla_3.14.1_win64-setup.exe" -singlelineoutput:yes -showoptions:no -showversion:no -database:"C:\test\db"
Invalid database name: c
~~~

A guess would be the `c:` in the path is causing the issue.  It doesn't seem to affect the full die.exe app, only the console.

I also tried a few different methods of quoting and no quoting. I even moved the option to be first. None of the methods worked.

* `-database:"C:\test\db"`
* `-database:"C:/test/db"`
* `-database:C:\test\db`
* `-database:""C:\test\db""`
* `-database:"C:\\test\\db"`
* `-database:""C:\\test\\db""`
* `-database:'C:\test\db'`
* `-database:''C:\test\db''`

I'm going to dig in a bit, but it appears that the colon in the database path is throwing for a loop. Any known workarounds?

**Comment by horsicq** [comment]
Thanks a lot for the bugreport! I have fixed it: https://github.com/horsicq/DIE-engine/commit/e943676a4d0ba4482506175da7b5375ee38fc85a
New version of DiE will be in 1-2 Months.

**Comment by ferventcoder** [comment]
I looked right at that last night. I was thinking prior to that it was something `QStringList arguments=QCoreApplication::arguments();` that was failing. 

Thanks! Now if I can just figure out how to build it optimized so it is not 455KB...

**Comment by horsicq** [comment]
// Now if I can just figure out how to build it optimized so it is not 455KB...

Try UPX http://upx.sourceforge.net/
upx --ultra-brute diec.exe

**Comment by ferventcoder** [comment]
Nice! 

~~~sh
c:\>choco install upx -y

Installing the following packages:
upx
By installing you accept licenses for the packages.

upx v3.91
Downloading upx
  from 'http://upx.sourceforge.net/download/upx391w.zip'

Progress: 100% - Saving 354.46 KB of 354.46 KB (362972/362972)
Download of 'upx391w.zip' (354.46 KB) completed.
Virus check: 0/56 scan engines flagged this assembly.
 Due to possible false positives we fail at 5 minimum positives.
 Virus scan engines indicate this file is probably safe. For details see
  https://www.virustotal.com/file/d7d4817f46d2616c209c46fb8bce44e4bec93ab5adef5e4dfc93ee879527be1b/analysis/
Hashes match.
Extracting C:\Users\rob\AppData\Local\Temp\chocolatey\upx\3.91\upx391w.zip to C:\ProgramData\chocolatey\lib\upx\tools...

C:\ProgramData\chocolatey\lib\upx\tools
 ShimGen has successfully created a shim for upx.exe
 The install of upx was successful.

Chocolatey installed 1/1 package(s). 0 package(s) failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

c:\>upx
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2013
UPX 3.91w       Markus Oberhumer, Laszlo Molnar & John Reiser   Sep 30th 2013
~~~

**Comment by horsicq** [comment]
:)
