### ISSUE TITLE
add tiny C compiler signature to database

### ISSUE THREAD

**Issue by graysuit** [horsicq/Detect-It-Easy#94]
Hi, Nice to meet again. Not sure from when, but continuously I used die a lot for PE analysis.
Nice work.

I'm working on C projects and will gonna heavily depend upon [tcc compiler](http://bellard.org/tcc).
Its extremely tiny but powerful C compiler. And also open source.

Currently, die shows `PE: linker: Microsoft Linker(6.0)[EXE32]`

I have analyzed some PE compiled by it and result is saved under **[data.html](https://github.com/horsicq/Detect-It-Easy/files/6986582/data.txt)**.

I also added some exe samples compiled by it. **[bin.zip](https://github.com/horsicq/Detect-It-Easy/files/6986573/bin.zip)**

**Comment by horsicq** [comment]
Hello! Thanks a lot for the files and the idea. I will add it to DiE

**Comment by horsicq** [comment]
Fixed: https://github.com/horsicq/Detect-It-Easy/commit/431af57a68b611a08b294c46effd1913d2a1f727

**Comment by graysuit** [comment]
Thanks you so much. 
From tests, it detects all exe compiled by tcc.

Here are my views on signature:

1.  Why need `if else`, if it has always to be detected at the end ? xD.
```js
If (has import 'msvcrt.dll' and Compiler Version is 6.0)
{
    if(...)
    {
        detected (line#15)
    }
    else
    {
        detected (line#25)
    }
    detected line#30
}
```
so I guess `detected line#30` is mistake.




2. This [GenOEP.dll](https://github.com/horsicq/Detect-It-Easy/files/7006231/GenOEP.dll.zip) detection looks doubtful:
```
PE: compiler: Microsoft Visual C/C++(6.0)[msvcrt]
PE: linker: Microsoft Linker(6.0)[DLL32]
PE: compiler: Tiny C Compiler(-)[-]
```
Because `Tiny C Compiler` can compile only C code. and `Visual C++` can compile both C/C++. 
But here, from my limited knowledge, I guess only one can occur can occur at a time.

This also looks to be wrong detected: [ZDRx.dll](https://github.com/horsicq/Detect-It-Easy/files/7006274/ZDRx.dll.zip)
```
PE: linker: unknown(6.0)[DLL32]
PE: compiler: Tiny C Compiler(-)[-]
```

**Conclusion:** detects all tcc based exe, but may wrong detect other exe as tcc based.

**Comment by horsicq** [comment]
It should now work: https://github.com/horsicq/Detect-It-Easy/blob/master/db/PE/Tiny%20C%20Compiler.sg

**Comment by graysuit** [comment]
Excellent job. Now it works great.
