### ISSUE TITLE
_denuvoComplete.2.sg False detection

### ISSUE THREAD

**Issue by LittleJay1985** [horsicq/Detect-It-Easy#95]
Denuvo falsely detected.

Script _denuvoComplete.2.sg on line 8:
 PE.findString()  returns -1 when string is not found

This results in:
    if (PE.isSectionNamePresent(".arch") || PE.isSectionNamePresent(".srdata") || PE.findString(0,1024,"Denuvo Timing"))
returning -1 instead of false

Proposing changing the line to:
    if (PE.isSectionNamePresent(".arch") || PE.isSectionNamePresent(".srdata") || PE.findString(0,1024,"Denuvo Timing")!=-1)
which would result in returning false if "Denuvo Timing" is not found and true if found

**Comment by LittleJay1985** [comment]
#96

**Comment by horsicq** [comment]
Thanks!
