### ISSUE TITLE
python not detected

### ISSUE THREAD

**Issue by megabugman** [horsicq/Detect-It-Easy#97]
![image](https://user-images.githubusercontent.com/17204819/133996358-2a341cd2-437e-42f9-a4f7-bbe0076c7846.png)

https://www.openshot.org/

**Comment by horsicq** [comment]
Thanks a lot for the bugeeport! I will take a look

**Comment by megabugman** [comment]
happy to help. you're fast :)

**Comment by horsicq** [comment]
Fixed: https://github.com/horsicq/Detect-It-Easy/commit/c73f0a93410fabdf76fc30d8c919d8d4d3e7b978
