### ISSUE TITLE
compilation error when building formatswidget.o

### ISSUE THREAD

**Issue by silverhikari** [horsicq/Detect-It-Easy#99]
../../die_script/pe_script.h:110:10: error: ‘RESOURCE_VERSION’ in ‘class XPE’ does not name a type
  110 |     XPE::RESOURCE_VERSION resourceVersion;
      |          ^~~~~~~~~~~~~~~~
../../FormatWidgets/formatswidget.cpp: In member function ‘void FormatsWidget::on_pushButtonPEVersion_clicked()’:
../../FormatWidgets/formatswidget.cpp:466:17: error: ‘TYPE_RESOURCE_VERSION’ is not a member of ‘SPE’; did you mean ‘TYPE_RESOURCES_VERSION’?
  466 |     showPE(SPE::TYPE_RESOURCE_VERSION);
      |                 ^~~~~~~~~~~~~~~~~~~~~
      |                 TYPE_RESOURCES_VERSION
make: *** [Makefile:15831: formatswidget.o] Error 1

**Comment by horsicq** [comment]
Tnanks a lot for the bugreport. Fixed.
